### ISSUE TITLE
Files damaged?

### ISSUE THREAD

**Issue by WilfredR** [matthewdias/fluidapps#1]
Hi Matthew,
I do have Fluidapp. However if I try to open your apps it says the file is damaged and I should put it in trash?

I'm on Yosimite

**Comment by matthewdias** [comment]
Apparently it didn't like simply copying the .app files. I've updated with basic instructions on how to create the app yourself using Fluid.

**Comment by WilfredR** [comment]
Thanks Matthew

I actually did in the mean time, but something very strange is going on with FB Messenger
- If I use Safari 8.0 agent I can’t type a message at all
- If I use Chrome agent. I can kind of type, but it doesnt show it, only when I press delete
- If I use Firefox agent, basically typing goes good, but I have an issue that the label “New Messages” is in the left panel, blocking the search field.

In each of the represented browsers themselves it works good.

Any clues?
Thanks,
Wilfred

**Comment by matthewdias** [comment]
Hm that's really odd. I'm having the same issues. For now I'd suggest using http://www.goofyapp.com while I take a closer look later and see what could be causing this.

**Comment by WilfredR** [comment]
I’m glad you have the same ;-) and you shouldn’t veel bad, because goofy is on the level of fluidapp with Chrome agent ;-)

Thanks for looking into it!

regs,
Wilfred
